### ISSUE TITLE
Minor Improvements

### ISSUE THREAD

**Issue by benjaminpfleghaar** [StephMode/quiz-app#10]
## index.html
Anstatt die Cards in eine `<section class="card-area">` zu platzieren, könntest du sie in einen `<main class="card-area"></main>` Container packen. Dann ist dein HTML-Grundgerüst aus semantischer Sicht perfekt.

Weiter könntest du deinen Buttons noch das Attribut `type="button"` geben, damit sie sich, wieder aus semantischer Sicht, von einem Submit-Button unterscheiden.

Im Footer kannst du dann noch deinen Links, also den `<a>` Tags ein `title="Link"` Attribut geben und jeweils den Link darin benennen. Screenreader mögen das 😉

## answer-button.js
Wie du richtig vermutest, gibt es einen Unterschied zwischen `querySelector` und `querySelectorAll`. Ersteres gibt dir **ein** Element zurück, während letzteres dir **alle** Elemente, auf die der Selektor passt, als Object zurückgibt.

Ansonsten gefällt mir dein Code, sehr schlank 🙌

**Comment by StephMode** [comment]
Vielen Dank, dass Du dir Zeit genommen hast, mein Projekt zu reviewen :) Deine Vorschläge waren für mich sehr hilfreich und ich habe sie daher implementiert.
